In [52]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [53]:
data = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
data.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [54]:
data.shape

(569, 33)

In [55]:
data.drop(['id', 'Unnamed: 32'], axis = 1, inplace= True)

In [56]:
data.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [57]:
X_train, X_test, y_train, y_test = train_test_split(data.iloc[:, 1:], data.iloc[:, 0], test_size= 0.2)

In [58]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [59]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [60]:
y_train

array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,

In [61]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [62]:
y_train_tensor.shape

torch.Size([455])

In [36]:
class simpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred, y):
        #clamp prediction to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1- epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss
        

In [72]:
import torch.nn as nn
class simpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [73]:
epochs = 500
learning_rate = 0.1

In [74]:
loss_function = nn.BCELoss()

In [76]:
!pip install torch==0.10.1

ERROR: Could not find a version that satisfies the requirement torch==0.10.1 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 2.0.0, 2.0.1, 2.1.0, 2.1.1, 2.1.2, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==0.10.1


In [77]:
import torch
print(torch.__version__)

2.1.2+cu121


In [75]:
model = simpleNN(X_train_tensor.shape[1])
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)
for epoch in range(epochs):
    y_pred = model(X_train_tensor)
    loss = loss_function(y_pred, y_train_tensor)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

c:\Users\admin\anaconda3\envs\nlp_transformer\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


InvalidVersion: Invalid version: '0.10.1,<0.11'

In [40]:
model = simpleNN(X_train_tensor)
for epoch in range(epochs):
    #do a forward pass
    y_pred = model.forward(X_train_tensor)
    #calculate the loss
    loss = model.loss_function(y_pred, y_train_tensor)
    #do a back prop
    loss.backward()
    #update the weight
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    #print loss 
    print(f'epoch - {epoch + 1}, loss: {loss.item()}')



epoch - 1, loss: 0.5230185461552356
epoch - 2, loss: 0.5082646274452822
epoch - 3, loss: 0.4939631133146857
epoch - 4, loss: 0.4801059165467835
epoch - 5, loss: 0.4666867502766439
epoch - 6, loss: 0.4533282403186138
epoch - 7, loss: 0.43837130404433977
epoch - 8, loss: 0.42389962209461407
epoch - 9, loss: 0.4099103545770715
epoch - 10, loss: 0.3963980192060639
epoch - 11, loss: 0.38335335257286646
epoch - 12, loss: 0.37076293677612415
epoch - 13, loss: 0.35860972344112657
epoch - 14, loss: 0.34687426510064034
epoch - 15, loss: 0.33553625774099516
epoch - 16, loss: 0.3245760000910925
epoch - 17, loss: 0.31397552374664467
epoch - 18, loss: 0.30371932587674144
epoch - 19, loss: 0.2937947566063674
epoch - 20, loss: 0.2841921565208951
epoch - 21, loss: 0.27490483272014016
epoch - 22, loss: 0.26592893031017956
epoch - 23, loss: 0.2572632228905146
epoch - 24, loss: 0.24890882038860926
epoch - 25, loss: 0.24086877964462078
epoch - 26, loss: 0.23314760332790066
epoch - 27, loss: 0.2257506266990

In [53]:
#model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.6).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(accuracy)

tensor(0.9825)


In [ ]:
for epoch in range(epochs):
    y_pred = self.we

SyntaxError: unexpected EOF while parsing (3688732500.py, line 1)

# autograd

In [2]:
import torch

In [13]:
x = torch.tensor(3, requires_grad= True, dtype = torch.float64)

In [14]:
y = x**2

In [15]:
y.backward()

In [16]:
y

tensor(9., dtype=torch.float64, grad_fn=<PowBackward0>)

In [17]:
print(x.grad)

tensor(6., dtype=torch.float64)


In [19]:
x = torch.tensor(6.8)
y = torch.tensor(1)

In [21]:
w = torch.tensor(1, requires_grad= True, dtype = torch.float32)
b = torch.tensor(0, requires_grad= True, dtype= torch.float32)

In [22]:
def binary_cross_entropy(prediction, target):
    epsilon = 1e-8
    pred = torch.clamp(prediction, epsilon, 1 - epsilon)
    prediction = -(target* torch.log(pred) + (1- target) * torch.log(1 - pred))
    return prediction
    


In [23]:
#forward pass 
z = w * x + b
y_pred = torch.sigmoid(z)

loss = binary_cross_entropy(y_pred, y)

In [24]:
loss

tensor(0.0011, grad_fn=<NegBackward0>)

In [26]:
x = torch.tensor([1, 2 , 3], requires_grad= True, dtype = torch.float32)

In [27]:
y = (x**2).mean()

In [28]:
y.backward()

In [29]:
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [30]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

# using torch.nn to create model

In [31]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out


In [32]:
features = torch.rand(10, 5)

# model object
model = SimpleNN(features.shape[1])

#model call for forward pass
model(features)


tensor([[0.4867],
        [0.5867],
        [0.4982],
        [0.5879],
        [0.5319],
        [0.5271],
        [0.6339],
        [0.5291],
        [0.5630],
        [0.5658]], grad_fn=<SigmoidBackward0>)

In [33]:

#weight and bias in linear layer
model.linear.weight

Parameter containing:
tensor([[ 0.1518, -0.1320, -0.3146,  0.2978,  0.3107]], requires_grad=True)

In [34]:
model.linear.bias

Parameter containing:
tensor([0.0767], requires_grad=True)

In [35]:
!pip install torchinfo

In [37]:
from torchinfo import summary
summary(model, input_size = (10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
SimpleNN                                 [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# now create a NN with a hidden layer with 3 neurons and relu then sigmoid on final layer

In [46]:
class MLP(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out = self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)


In [47]:
mlp = MLP(features.shape[1])

In [48]:
mlp(features)

In [49]:
mlp.linear1.weight

Parameter containing:
tensor([[ 0.4101,  0.2632, -0.0970,  0.0431, -0.3354],
        [-0.3705,  0.2177,  0.0926, -0.3017, -0.0518],
        [ 0.4374, -0.2026, -0.1898, -0.1137, -0.2194]], requires_grad=True)

In [50]:
mlp.linear1.bias

Parameter containing:
tensor([ 0.0446,  0.3816, -0.3284], requires_grad=True)

In [39]:
# using container to write this
class MLP(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 3),
            nn.ReLU(),
            nn.Linear(3, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [51]:
summary(mlp, input_size= (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
MLP                                      --                        --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00